import { Metadata } from "next"
import Link from "next/link"

export const metadata:Metadata = {
  title:{
    default:"NextJS - Pavan",
    template:"%s | Pavan"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header style={{backgroundColor:"blueviolet", padding:"1rem"}}>
          <p>header</p>
          <Link href="/">Home</Link>
        </header>

          {children}

        <footer style={{backgroundColor:"greenyellow", padding:"1rem"}}>
          <p>footer</p>
        </footer>
        </body>
      
    </html>
  )
}
