export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header style={{backgroundColor:"blueviolet", padding:"1rem"}}>
          <p>header</p>
        </header>

          {children}

        <footer style={{backgroundColor:"greenyellow", padding:"1rem"}}>
          <p>footer</p>
        </footer>
        </body>
      
    </html>
  )
}
